# Generated by Django 5.2.3 on 2026-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
    ]
