# Generated by Django 5.2.3 on 2026-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Provider', '0002_attacklog_is_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
