# Generated by Django 4.2.23 on 2025-07-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cyber_attack_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.TextField(blank=True, null=True)),
                ('Timestamp', models.TextField(blank=True, null=True)),
                ('Source_IP_Address', models.TextField(blank=True, null=True)),
                ('Destination_IP_Address', models.TextField(blank=True, null=True)),
                ('Source_Port', models.TextField(blank=True, null=True)),
                ('Destination_Port', models.TextField(blank=True, null=True)),
                ('Protocol', models.TextField(blank=True, null=True)),
                ('Packet_Length', models.TextField(blank=True, null=True)),
                ('Packet_Type', models.TextField(blank=True, null=True)),
                ('Traffic_Type', models.TextField(blank=True, null=True)),
                ('Payload_Data', models.TextField(blank=True, null=True)),
                ('Malware_Indicators', models.TextField(blank=True, null=True)),
                ('Anomaly_Scores', models.TextField(blank=True, null=True)),
                ('Alerts_Warnings', models.TextField(blank=True, null=True)),
                ('Attack_Signature', models.TextField(blank=True, null=True)),
                ('Action_Taken', models.TextField(blank=True, null=True)),
                ('Severity_Level', models.TextField(blank=True, null=True)),
                ('Device_Information', models.TextField(blank=True, null=True)),
                ('Network_Segment', models.TextField(blank=True, null=True)),
                ('Geo_City_location_Data', models.TextField(blank=True, null=True)),
                ('Proxy_Information', models.TextField(blank=True, null=True)),
                ('Firewall_Logs', models.TextField(blank=True, null=True)),
                ('IDS_IPS_Alerts', models.TextField(blank=True, null=True)),
                ('Log_Source', models.TextField(blank=True, null=True)),
                ('Prediction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
