# Generated by Django 4.2.23 on 2025-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection_accuracy',
            name='ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detection_ratio',
            name='ratio',
            field=models.FloatField(),
        ),
    ]
