# Generated by Django 5.2.3 on 2026-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0002_alter_detection_accuracy_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
