# Generated by Django 5.2.3 on 2026-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0003_alter_clientregister_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
