# Generated by Django 5.2.3 on 2026-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0004_alter_clientregister_model_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregister_model',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
