# Generated by Django 5.2.3 on 2026-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0005_clientregister_model_email_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
