# Generated by Django 5.2.3 on 2026-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0006_alter_clientregister_model_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientregister_model',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='clientregister_model',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='clientregister_model',
            name='is_mobile_verified',
        ),
        migrations.RemoveField(
            model_name='clientregister_model',
            name='mobile_otp',
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
