# Generated by Django 5.2.3 on 2026-03-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_remove_clientregister_model_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregister_model',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
